#!/usr/bin/env bash

CBUILD_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$CBUILD_ROOT/.env" #Carrega variáveis utilizadas pelos arquivos do projeto

case "$1" in
    build) echo "comando build" ;;
    clean) echo "comando clean" ;;
    test) source "${CBUILD_ROOT}/tests/test.sh" $ARGS ;;
    *)
        echo "Uso: cbuild {build|clean}"
        exit 1
    ;;
esac